run-example1:
	jexl-executor context.json script1.jexl

run-example2:
	jexl-executor context.json script2.jexl

run-example3:
	jexl-executor context.json script3.jexl

run-example2-e:
	jexl-executor -e '@file:exit.jexl' context.json script2.jexl
