$ErrorActionPreference = 'Stop'

$RepoRoot = Split-Path -Parent $PSScriptRoot
Set-Location -LiteralPath $RepoRoot

$releasePs1 = Join-Path $RepoRoot 'release.ps1'
if (-not (Test-Path -LiteralPath $releasePs1)) {
    throw "release.ps1 not found: $releasePs1"
}
. $releasePs1
if ([string]::IsNullOrWhiteSpace($ReleaseVersion)) {
    throw '$ReleaseVersion is not set or empty in release.ps1'
}
if ([string]::IsNullOrWhiteSpace($ReleasePackageName)) {
    throw '$ReleasePackageName is not set or empty in release.ps1'
}
if ([string]::IsNullOrWhiteSpace($ReleaseVendor)) {
    throw '$ReleaseVendor is not set or empty in release.ps1'
}
$VERSION = $ReleaseVersion
$PACKAGE_NAME = $ReleasePackageName
$VENDOR = $ReleaseVendor

$jar = Join-Path (Join-Path $RepoRoot 'target') "${PACKAGE_NAME}.jar"
if (-not (Test-Path -LiteralPath $jar)) {
    throw "JAR not found: $jar (run Maven package from repo root first)"
}

$jpackageRoot = Join-Path $RepoRoot 'jpackage'
$inputDir = Join-Path $jpackageRoot 'input'
$runtimeDir = Join-Path $jpackageRoot 'runtime'

New-Item -ItemType Directory -Force -Path $inputDir | Out-Null
Copy-Item -LiteralPath $jar -Destination (Join-Path $inputDir (Split-Path -Leaf $jar)) -Force

$depsLines = & jdeps.exe --print-module-deps --ignore-missing-deps --multi-release 21 $jar
if ($LASTEXITCODE -ne 0) {
    throw "jdeps failed with exit code $LASTEXITCODE"
}
$deps = (($depsLines | ForEach-Object { $_.ToString().Trim() }) | Where-Object { $_ }) -join ','
if ([string]::IsNullOrWhiteSpace($deps)) {
    throw 'jdeps returned no module list (--print-module-deps)'
}

& jlink.exe --add-modules $deps --output $runtimeDir --no-header-files --no-man-pages
if ($LASTEXITCODE -ne 0) {
    throw "jlink failed with exit code $LASTEXITCODE"
}

Push-Location -LiteralPath $jpackageRoot
try {
    $mainJar = "${PACKAGE_NAME}.jar"
    & jpackage.exe `
        --type app-image `
        --name $PACKAGE_NAME `
        --input input `
        --main-jar $mainJar `
        --runtime-image runtime `
        --app-version $VERSION `
        --win-console `
        --vendor $VENDOR
    if ($LASTEXITCODE -ne 0) {
        throw "jpackage failed with exit code $LASTEXITCODE"
    }

    # WinGet portable installs put a symlink under %LOCALAPDATA%\Microsoft\WinGet\Links\ that
    # points at the packaged binary. jpackage's native .exe resolves jexl-executor.cfg from the
    # symlink path (Links\...) instead of the real install dir, so the launcher fails before JVM
    # starts. A .cmd wrapper in the package root uses %~dp0 (the real extracted location) and
    # invokes the jpackaged exe there. WinGet can symlink jexl-executor.exe to jexl-executor.cmd
    # (see e.g. Apache.Maven portable). Update winget NestedInstallerFiles RelativeFilePath to
    # this .cmd (not the inner .exe) when publishing.
    $wrapperName = "${PACKAGE_NAME}.cmd"
    $wrapperPath = Join-Path (Get-Location) $wrapperName
    $innerExeRel = "${PACKAGE_NAME}\${PACKAGE_NAME}.exe"
    @"
@echo off
REM Generated by build-windows-zip.ps1 - see script comments for WinGet + jpackage.
"%~dp0${innerExeRel}" %*
exit /b %ERRORLEVEL%
"@ | Set-Content -LiteralPath $wrapperPath -Encoding ascii

    $zipName = "${PACKAGE_NAME}-${VERSION}-windows-x64.zip"
    $zipPath = Join-Path $RepoRoot $zipName
    if (Test-Path -LiteralPath $zipPath) {
        Remove-Item -LiteralPath $zipPath -Force
    }
    Compress-Archive -Path @($wrapperName, $PACKAGE_NAME) -DestinationPath $zipPath -CompressionLevel Optimal
    Remove-Item -LiteralPath $wrapperPath -Force
}
finally {
    Pop-Location
}
